{% set name = "bump-my-version" %}
{% set version = "1.2.4" %}
{% set build_number = 0 %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 998abb4f3774cf96137a77034a5a12a722b109b26a3afa044ec14622a0180fa3

build:
  number: {{ build_number }}
  entry_points:
    - bump-my-version = bumpversion.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.25.0
    - pip
  run:
    - python >={{ python_min }}
    - click <8.2.2
    - httpx
    - pydantic >=2.0.0
    - pydantic-settings
    - questionary
    - rich-click
    - rich
    - tomlkit
    - wcmatch >=8.5.1

test:
  imports:
    - bumpversion
  commands:
    - pip check
    - bump-my-version --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/callowayproject/bump-my-version
  summary: Version bump your Python project
  description: >-
    A small command line tool to simplify releasing software by updating all version strings in your source code by the correct increment and optionally commit and tag the changes.

    * version formats are highly configurable * works without any source code manager, but happily reads tag information from and writes commits and tags to Git and Mercurial if available * just handles text files, so it's not specific to any programming language * supports Python 3.8+ and PyPy3. Python 3.7 should work but
    isn't actively tested.
  license: MIT
  license_file: LICENSE
  doc_url: https://callowayproject.github.io/bump-my-version/

extra:
  recipe-maintainers:
    - coordt
    - mfisher87
