{% set name = "bump-my-version" %}
{% set version = "0.12.0" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f5a4bd0d07e6338b0ac1b5e48188934cc6d529da91e147be786fd616236813d

build:
  number: {{ build_number }}
  entry_points:
    - bump-my-version = bumpversion.cli:cli
    - bumpversion = bumpversion.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools >=40.9.0
    - wheel
    - pip
  run:
    - python >=3.8
    - click
    - pydantic <2.0.0
    - rich-click
    - rich
    - tomlkit

test:
  imports:
    - bumpversion
  commands:
    - pip check
    - bump-my-version --help
    - bumpversion --help
  requires:
    - pip

about:
  home: https://github.com/callowayproject/bump-my-version
  summary: Version bump your Python project
  description: >-
    A small command line tool to simplify releasing software by updating all version strings in your source code by the correct increment and optionally commit and tag the changes.

    * version formats are highly configurable * works without any source code manager, but happily reads tag information from and writes commits and tags to Git and Mercurial if available * just handles text files, so it's not specific to any programming language * supports Python 3.8+ and PyPy3. Python 3.7 should work but
    isn't actively tested.
  license: MIT
  license_file: LICENSE
  doc_url: https://callowayproject.github.io/bump-my-version/

extra:
  recipe-maintainers:
    - coordt
    - mfisher87
